version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - canonicalheader
    - errcheck
    - errchkjson
    - errname
    - govet
    - ineffassign
    - unused
    - wsl_v5
  settings:
    wsl_v5:
      disable:
        - if
formatters:
  enable:
    - gofmt
